### ISSUE TITLE
Project wrap up

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/principle-inhaler-uptake#59]
from @brianmackenna 

- [x] deposit the Letter with Wellcome Open Research

- [ ] IG to decide what project to assign to

- [ ] close it on Job Server

**Comment by Jongmassey** [comment]
@amirmehrkar and @LiamHart-hub taking on issue of project (non-)allocation. Will close when resolved

**Comment by Jongmassey** [comment]
These actions are now with IG

**Comment by LiamHart-hub** [comment]
Hello @Jongmassey, 

Just for confirmation, please can you state which approved project this refers to, so I can check up on this since I have been away on A/L? 

Thanks

**Comment by Jongmassey** [comment]
We've been round and round several times on this. This doesn't refer to an approved project. I'm not willing to arbitrarily choose one to post-hoc allocate it to

**Comment by LiamHart-hub** [comment]
Okay, I know what you are referring to now, but just to wanted to double check here. Thanks
